export const USERAPI = {
    "login": "uahm93",
    "id": 42427081,
    "node_id": "MDQ6VXNlcjQyNDI3MDgx",
    "avatar_url": "https://avatars.githubusercontent.com/u/42427081?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/uahm93",
    "html_url": "https://github.com/uahm93",
    "followers_url": "https://api.github.com/users/uahm93/followers",
    "following_url": "https://api.github.com/users/uahm93/following{/other_user}",
    "gists_url": "https://api.github.com/users/uahm93/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/uahm93/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/uahm93/subscriptions",
    "organizations_url": "https://api.github.com/users/uahm93/orgs",
    "repos_url": "https://api.github.com/users/uahm93/repos",
    "events_url": "https://api.github.com/users/uahm93/events{/privacy}",
    "received_events_url": "https://api.github.com/users/uahm93/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ulises H. Mendoza",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Ingeniero de software\r\nDesarrollador Full Stack",
    "twitter_username": null,
    "public_repos": 22,
    "public_gists": 0,
    "followers": 0,
    "following": 0
  }